version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: partie
      MYSQL_USER: partie
      MYSQL_PASSWORD: partie
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: ./backend
    command: flask run --host=0.0.0.0
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://partie:partie@db/partie
      JWT_SECRET_KEY: dev
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  db_data:
